baseURL = "//trypyramid.com/"

languageCode = "en-us"
title = "Welcome to Pyramid, a Python Web Framework"
googleAnalytics = "UA-21146943-3"

enableGitInfo = true

uglyurls = true

disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]
